<?php
/*
 *		This Source Code Form is subject to the terms 
 *		of the Mozilla Public License, v. 2.0. If a copy 
 *		of the MPL was not distributed with this file, 
 *		You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * 		Copyright (c) 2012 Balazs Pete, UCD Science Society
 */
 
/*
 *		A script to generate a CSS stylesheet based on information stored in a database
 *		Use the MYSQL query in main_style.sql to create a styles table in your database
 */

header('Content-type: text/css;Character');//sets the type of the php file to css

$compress = false;
$compress_n = '
';
$compress_t = '	';
	
// if stylesheet is to be compressed/minified
if(!isset($_GET['compress']) || $_GET['compress']==1){	
	$compress = true;
	$compress_n = '';
	$compress_t = '';
}

$legal_require_php = 1234; // a variable to restrict file inclusion
require('../dbconnect.php'); // require mysql connection settings

//get every tuple from styles table
$result = mysql_query("SELECT * FROM styles");

$cssFile = "main_style.css";
$fh = fopen($cssFile, 'w');
$towrite = "@charset \"utf-8\";\n/* CSS Document */\n$compress_n/* This css file has been generated by the main_style.php script */\n$compress_n/* To refresh with new data, call the php script */\n";
if($compress){
	$towrite = $towrite."/* The stylesheet has been minified */\n\n";
}

fwrite($fh,$towrite);
echo $towrite;

//generating the css page from data in the styles table
while($row = mysql_fetch_array($result)){
	
	$key_array = array_keys($row);//returns an array of the columns in the table (each column appears twice; 1 - the number of the column, 2 - the name of the column)
	
	$count = 3;//counter (number of columns) start at 3, as 1st column is grouping info
	$towrite = $row['ref']." {";
	fwrite($fh, $towrite);//ref - html tag name
	echo "$towrite";
	while($count<(sizeof($key_array)/2)){// array/2 = number of columns
		if($row[$count]!=null){//if the entry in the column is not empty, if null then nothing will be written for that property -> increases loading and browser performance
			$towrite = "$compress_n$compress_t".$key_array[$count*2+1].":".$row[$count].";";
			fwrite($fh,$towrite);//result -> 	property:value;
			echo $towrite;
		}
		$count++;//goto next column
	}
	$towrite = "$compress_n}$compress_n$compress_n";
	fwrite($fh,$towrite);//close tag css
	echo $towrite;
	$count=0;//reset count
}

fclose($fh);
mysql_close($con);


?>


